<?php

namespace Database\Seeders;

use App\Models\witel;
use App\Models\sto;
use App\Models\UsulanOLT;
use Illuminate\Database\Seeder;

class UsulanOLTSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public static function run()
    {
        UsulanOLT::insert([
            ['witel_id' => UsulanOLTSeeder::findWitel('JEMBER'),'sto_id' => UsulanOLTSeeder::findSTO('MUNCAR'),'kode_sto' => 'MCR','alamat' => 'CURAH JATI','lat' => '-8,548713','long' => '114,24429','merk' => 'ZTE','tipe' => 'C620','tahap_pemenuhan' => 'Q2 (APR 2022)','pln' => 'YES','uplink' => 'YES','metro' => 'MCR','jarak_sto' => '19,5','sitac' => 'YES','jml_odp' => '13','kebutuhan' => 'TCLOUD, STTF2','prioritas' => '1','propose_box' => 'OLT ONLY, WITHOUT BOX','jadwal_order' => 'April 2022-preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('JEMBER'),'sto_id' => UsulanOLTSeeder::findSTO('MUNCAR'),'kode_sto' => 'BCK','alamat' => 'GRAJAGAN','lat' => '-8,593813','long' => '114,222623','merk' => 'ZTE','tipe' => 'C620','tahap_pemenuhan' => 'Q2 (APR 2022)','pln' => 'YES','uplink' => 'NOT YET, NDE USULAN UPGRADE SUDAH DI APPROVE]','metro' => 'MCR','jarak_sto' => '27,1','sitac' => 'YES','jml_odp' => '4','kebutuhan' => 'TCLOUD, STTF2','prioritas' => '1','propose_box' => 'OLT ONLY, WITHOUT BOX','jadwal_order' => 'April 2022-preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('JEMBER'),'sto_id' => UsulanOLTSeeder::findSTO('ROGOJAMPI'),'kode_sto' => 'RGJ','alamat' => 'SERAGI','lat' => '-8,234263','long' => '114,202875','merk' => 'ZTE','tipe' => 'C620','tahap_pemenuhan' => 'Q2','pln' => 'NO','uplink' => 'YES','metro' => 'RGJ','jarak_sto' => '13,8','sitac' => 'YES','jml_odp' => '5','kebutuhan' => 'TCLOUD, STTF2','prioritas' => '1','propose_box' => 'OLT ONLY, WITHOUT BOX','jadwal_order' => 'April 2022-preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('JEMBER'),'sto_id' => UsulanOLTSeeder::findSTO('TANGGUL'),'kode_sto' => 'TGU','alamat' => 'DEPAN BALAI DESA PALERAN','lat' => '-8,229423','long' => '113,491966','merk' => 'ZTE','tipe' => 'C620','tahap_pemenuhan' => 'Q1','pln' => 'YES','uplink' => 'YES','metro' => 'TGU','jarak_sto' => '13','sitac' => 'YES','jml_odp' => NULL,'kebutuhan' => 'TCLOUD, STTF2','prioritas' => '1','propose_box' => 'OLT ONLY, WITHOUT BOX','jadwal_order' => 'April 2022-preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('JEMBER'),'sto_id' => UsulanOLTSeeder::findSTO('BESUKI'),'kode_sto' => 'BKI','alamat' => 'KANTOR STO BESUKI','lat' => NULL,'long' => NULL,'merk' => 'ZTE','tipe' => 'C600','tahap_pemenuhan' => NULL,'pln' => 'YES','uplink' => 'N/A','metro' => 'BKI','jarak_sto' => '0','sitac' => 'YES','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('DENPASAR'),'sto_id' => UsulanOLTSeeder::findSTO('BENOA'),'kode_sto' => 'BNO','alamat' => 'Mertasari/Suwung Batan Kendal','lat' => '-8,704992','long' => '115,233899','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'NO','jarak_sto' => '3','sitac' => 'NO','jml_odp' => '5','kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('DENPASAR'),'sto_id' => UsulanOLTSeeder::findSTO('JIMBARAN'),'kode_sto' => 'JBR','alamat' => 'Puri Gading','lat' => '-8,803886','long' => '115,159454','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'NO','jarak_sto' => '4,6','sitac' => 'NO','jml_odp' => '15','kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('DENPASAR'),'sto_id' => UsulanOLTSeeder::findSTO('UBUNG'),'kode_sto' => 'UBN','alamat' => 'Pasar Bringkit','lat' => '-8,561852','long' => '115,160445','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'NO','jarak_sto' => '12','sitac' => 'NO','jml_odp' => '4','kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('DENPASAR'),'sto_id' => UsulanOLTSeeder::findSTO('JIMBARAN'),'kode_sto' => 'JBR','alamat' => 'Goa Gong','lat' => '-8,817467156','long' => '115,1731102','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => NULL,'metro' => NULL,'jarak_sto' => NULL,'sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('DENPASAR'),'sto_id' => UsulanOLTSeeder::findSTO('NUSA DUA'),'kode_sto' => 'NDA','alamat' => 'Dharmawangsa','lat' => '-8,80511','long' => '115,20433','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => NULL,'metro' => NULL,'jarak_sto' => NULL,'sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('DENPASAR'),'sto_id' => UsulanOLTSeeder::findSTO('NUSA DUA'),'kode_sto' => 'NDA','alamat' => 'Bukit Kampial','lat' => '-8,82002','long' => '115,18948','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'yes','metro' => NULL,'jarak_sto' => NULL,'sitac' => 'YES','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('KEDIRI'),'sto_id' => UsulanOLTSeeder::findSTO('NGANJUK'),'kode_sto' => 'NJK','alamat' => 'Ngetos Berbek Kuncir','lat' => '-7,675354','long' => '111,848107','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'No','uplink' => 'No','metro' => NULL,'jarak_sto' => '11,6','sitac' => 'Yes','jml_odp' => NULL,'kebutuhan' => 'tcloud','prioritas' => 'OGP deploy','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('KEDIRI'),'sto_id' => UsulanOLTSeeder::findSTO('BLITAR'),'kode_sto' => 'BLR','alamat' => 'Suruhwadang','lat' => '-8,196312','long' => '112,104485','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'No','uplink' => 'No','metro' => NULL,'jarak_sto' => '14,7','sitac' => 'Yes','jml_odp' => NULL,'kebutuhan' => 'sttf','prioritas' => 'OGP deploy','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('KEDIRI'),'sto_id' => UsulanOLTSeeder::findSTO('TRENGGALEK'),'kode_sto' => 'TRE','alamat' => 'PULE TRENGGALEK','lat' => '-8,096013','long' => '111,582863','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'No','uplink' => 'OGP ','metro' => NULL,'jarak_sto' => '15,6','sitac' => 'No','jml_odp' => NULL,'kebutuhan' => 'Fiberasisai NJKI area outer Trenggalek , nunggu distribusi','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('KEDIRI'),'sto_id' => UsulanOLTSeeder::findSTO('LODOYO'),'kode_sto' => 'LDY','alamat' => 'PANGGUNGREJO','lat' => '-8,255983','long' => '112,275856','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'No','uplink' => 'YES','metro' => NULL,'jarak_sto' => '13,7','sitac' => 'No','jml_odp' => NULL,'kebutuhan' => 'STTF 2 (Potensial)','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => 'April 22, preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('KEDIRI'),'sto_id' => UsulanOLTSeeder::findSTO('MOJOROTO'),'kode_sto' => 'MJT','alamat' => 'MOJOROTO TAROKAN','lat' => '-7,731889','long' => '111,951484','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'No','uplink' => 'YES','metro' => NULL,'jarak_sto' => '12,2','sitac' => 'No','jml_odp' => NULL,'kebutuhan' => 'STTF 2 (Potensial]','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => 'April 22, preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('BOJONEGORO'),'kode_sto' => 'BJN','alamat' => 'PASAR DANDER','lat' => '-7,24815','long' => '111,84812','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-BJ','jarak_sto' => '12,1','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022, STTF-1 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => 'April 22-preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('LOROG'),'kode_sto' => 'LOG','alamat' => 'TULAKAN','lat' => '-8,172506','long' => '111,275221','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-PN','jarak_sto' => '11,2','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022, STTF-1 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('MAGETAN'),'kode_sto' => 'MGT','alamat' => 'PSR KERTEN','lat' => '-7,476734','long' => '111,342634','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MGT','jarak_sto' => '15','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => 'April 22-preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('MAGETAN'),'kode_sto' => 'MGT','alamat' => 'LEMBEYAN','lat' => '-7,7609','long' => '111,4012','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MGT','jarak_sto' => '10,6','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022, STTF-1 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('NGAWI'),'kode_sto' => 'NWI','alamat' => 'GUYUNG-GERIH','lat' => '-7,518926','long' => '111,388264','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME2-D5-NW','jarak_sto' => '15,4','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022, STTF-1 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => 'April 22-preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('PADANGAN'),'kode_sto' => 'PAD','alamat' => 'SAMBENG','lat' => '-713.835','long' => '11.162.235','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NO','metro' => 'ME-D5-PAD','jarak_sto' => '22,1','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('SUMBERREJO'),'kode_sto' => 'SMJ','alamat' => 'KEDUNGADEM FE','lat' => '-7,30337','long' => '112,046719','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-SBR','jarak_sto' => '10,3','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('BOJONEGORO'),'kode_sto' => 'BJN','alamat' => 'SUKOSEWU','lat' => '-7,259461','long' => '111,924103','merk' => 'HUAWEI','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-BJ','jarak_sto' => '15,4','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('BOJONEGORO'),'kode_sto' => 'BJN','alamat' => 'TRUCUK','lat' => '-7,154539','long' => '111,869129','merk' => 'HUAWEI','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-BJ','jarak_sto' => '1,8','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('CARUBAN'),'kode_sto' => 'CRB','alamat' => 'SUMBERSARI','lat' => '-7,5232743','long' => '111,6921307','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-CRB','jarak_sto' => '7,2','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('KALITIDU'),'kode_sto' => 'KDU','alamat' => 'MALO','lat' => '-7,10914','long' => '111,73057','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-KDU','jarak_sto' => '6,3','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('KARANGJATI'),'kode_sto' => 'KRJ','alamat' => 'KEDUNG PRAHU','lat' => '-7,4446867','long' => '111,5536744','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-KRJ','jarak_sto' => '7,3','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('KEREK'),'kode_sto' => 'KRK','alamat' => 'MONTONG','lat' => '-6,949792','long' => '111,880935','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-KRK','jarak_sto' => '7,6','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('MADIUN'),'kode_sto' => 'MNZ','alamat' => 'NGLAMES','lat' => '-7,592039','long' => '111,538058','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MN','jarak_sto' => '4,3','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('MADIUN'),'kode_sto' => 'MNZ','alamat' => 'TAKERAN','lat' => '-7,6590508','long' => '111,5074049','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MN','jarak_sto' => '4,7','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('SUMOROTO'),'kode_sto' => 'SMO','alamat' => 'BADEGAN','lat' => '-7,87238','long' => '111,328191','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-SMO','jarak_sto' => '8,9','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022, STTF-1 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('MAGETAN'),'kode_sto' => 'MGT','alamat' => 'SIDOREJO','lat' => '-7,657262','long' => '111,279568','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MGT','jarak_sto' => '6','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('MAOSPATI'),'kode_sto' => 'MSP','alamat' => 'TEMBORO','lat' => '-7,5883986','long' => '111,3990922','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MPT','jarak_sto' => '6,4','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('NGAWI'),'kode_sto' => 'NWI','alamat' => 'NGALE','lat' => '-7,395459969','long' => '111,370175','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME2-D5-NW','jarak_sto' => '9,2','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('PACITAN'),'kode_sto' => 'PNZ','alamat' => 'KEBON AGUNG','lat' => '-8,214328737','long' => '111,1497751','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-PN','jarak_sto' => '7,3','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('PADANGAN'),'kode_sto' => 'PAD','alamat' => 'GAYAM','lat' => '-7,13712','long' => '111,726','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-PAD','jarak_sto' => '5,5','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('PONOROGO'),'kode_sto' => 'PON','alamat' => 'MLILIR','lat' => '-7,7974325','long' => '111,5133747','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-PO','jarak_sto' => '5,8','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('PONOROGO'),'kode_sto' => 'PON','alamat' => 'DANYANG','lat' => '-7,8003','long' => '111,4576','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-PO','jarak_sto' => '8,7','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('PUNUNG'),'kode_sto' => 'PNG','alamat' => 'PRINGKUKU','lat' => '-8,1573869','long' => '111,0330955','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-PUN','jarak_sto' => '4,2','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('SUMBERREJO'),'kode_sto' => 'SMJ','alamat' => 'BALEN','lat' => '-7,192472','long' => '111,959278','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-SMJ','jarak_sto' => '4,7','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('SUMBERREJO'),'kode_sto' => 'SMJ','alamat' => 'MEDALEM','lat' => '-7,16689','long' => '112,035452','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-SMJ','jarak_sto' => '4,4','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('SUMBERREJO'),'kode_sto' => 'SMJ','alamat' => 'KEPOHBARU','lat' => '-7,22896','long' => '112,08726','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-SMJ','jarak_sto' => '17,9','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => 'April 22-preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('TUBAN'),'kode_sto' => 'TNZ','alamat' => 'PENAMBANGAN','lat' => '-6,934898','long' => '112,058234','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NO','metro' => 'ME-D5-TN','jarak_sto' => '8,2','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADIUN'),'sto_id' => UsulanOLTSeeder::findSTO('WALIKUKUN'),'kode_sto' => 'WKU','alamat' => 'SIDOLAJU','lat' => '-7,403921024','long' => '111,260742','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-WKU','jarak_sto' => '9,2','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'FEEDERISASI 2022','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('BANGKALAN'),'kode_sto' => 'BKL','alamat' => 'KEC. KWANNYAR','lat' => '-7,154848','long' => '112,859704','merk' => 'HUAWEI','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'PROPOSE','metro' => NULL,'jarak_sto' => '19,7','sitac' => 'PROPOSE','jml_odp' => NULL,'kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => 'April 2022, preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('PAMEKASAN'),'kode_sto' => 'PME','alamat' => 'KEC. PROPO','lat' => '-7,126292','long' => '113,40921','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '10,2','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('SAMPANG'),'kode_sto' => 'SPG','alamat' => 'KEC. PENGARENGAN','lat' => '-7,199658','long' => '113,153381','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '13,6','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('KETAPANG'),'kode_sto' => 'KPP','alamat' => 'KEC. ROBATAL','lat' => '-7,00114','long' => '113,281','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => NULL,'jarak_sto' => '24,7','sitac' => 'PROPOSE','jml_odp' => '13','kebutuhan' => 'STTF Batch 2','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => 'April 2022, preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('SAMPANG'),'kode_sto' => 'KPP','alamat' => 'KEC. SOKOBANAH','lat' => '-7,050963','long' => '113,254486','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '16,8','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('SAMPANG'),'kode_sto' => 'SPG','alamat' => 'KEC. TAMBELANGAN','lat' => '-7,045892','long' => '113,168633','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'PROPOSE','metro' => NULL,'jarak_sto' => '23,3','sitac' => 'PROPOSE','jml_odp' => '23','kebutuhan' => 'STTF Batch 2','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => 'April 2022, preorder thp3'],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('SUMENEP'),'kode_sto' => 'SMP','alamat' => 'KEC. BATUPUTIH','lat' => '-6,990004','long' => '113,818871','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '8,3','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('PAMEKASAN'),'kode_sto' => 'PME','alamat' => 'KEC. TALANG SIRING','lat' => '-7,135466','long' => '113,570866','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '12,1','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('SUMENEP'),'kode_sto' => 'SMP','alamat' => 'KEC. BLUTO','lat' => '-7,09383','long' => '113,775156','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NO','metro' => NULL,'jarak_sto' => '17,7','sitac' => 'NO','jml_odp' => '31','kebutuhan' => 'STTF Batch 3','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('AMBUNTEN'),'kode_sto' => 'ABT','alamat' => 'KEC. DASUK','lat' => '-6,905193','long' => '113,81638','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NO','metro' => NULL,'jarak_sto' => '11,3','sitac' => 'NO','jml_odp' => '21','kebutuhan' => 'STTF Batch 3','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MADURA'),'sto_id' => UsulanOLTSeeder::findSTO('OMBEN'),'kode_sto' => 'OMB','alamat' => 'KEC. PALENGAAN','lat' => '-7,062437','long' => '113,432303','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NO','metro' => NULL,'jarak_sto' => '21,8','sitac' => 'NO','jml_odp' => '62','kebutuhan' => 'STTF Batch 3','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('SAWOJAJAR'),'kode_sto' => 'SWJ','alamat' => 'AMPELDENTO','lat' => '-7,9871112','long' => '112,6812332','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NO','metro' => 'ME2-D5-SWJ','jarak_sto' => '3,5','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'Reboundry  (catuan ikut Mlg Kota)','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('SAWOJAJAR'),'kode_sto' => 'SWJ','alamat' => 'KEDUNGKANDANG','lat' => '-7,98291','long' => '112,6728','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => NULL,'metro' => NULL,'jarak_sto' => '1,5','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('NGANTANG'),'kode_sto' => 'NTG','alamat' => 'PASAR LAJU','lat' => '-7,815483','long' => '112,372522','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => NULL,'metro' => NULL,'jarak_sto' => '4,8','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('BATU'),'kode_sto' => 'BTU','alamat' => 'COBAN RONDO','lat' => '-7,866522','long' => '112,491503','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => NULL,'metro' => NULL,'jarak_sto' => '4,2','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('PAGAK'),'kode_sto' => 'PGK','alamat' => 'ARJOWILANGUN/ SUKOWILANGUN','lat' => '-8,191533','long' => '112,422486','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => NULL,'metro' => NULL,'jarak_sto' => '15,7','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('BLIMBING'),'kode_sto' => 'BLB','alamat' => 'PERUM TIRTASANI','lat' => '-7,907031','long' => '112,63145','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME2-D5-BLB','jarak_sto' => '5,8','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'Reboundry ( catuan jauh dr sto )','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('KLOJEN'),'kode_sto' => 'KLJ','alamat' => 'KUCUR','lat' => '-7,956169','long' => '112,512414','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => NULL,'metro' => NULL,'jarak_sto' => '14,6','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('KEPANJEN'),'kode_sto' => 'KEP','alamat' => 'NGAJUM','lat' => '-8,1273256','long' => '112,5557116','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'YES','uplink' => NULL,'metro' => NULL,'jarak_sto' => '2,1','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            ['witel_id' => UsulanOLTSeeder::findWitel('MALANG'),'sto_id' => UsulanOLTSeeder::findSTO('TUMPANG'),'kode_sto' => 'TMP','alamat' => 'Miniolt Desa Ngadas','lat' => '-7,983699','long' => '112,90814','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'NO','metro' => 'ME-D5-TMP','jarak_sto' => '21,1','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'Usulan daerah Wisata','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('BIMA'),'kode_sto' => 'BMA','alamat' => 'KOLO','lat' => '-8,372825','long' => '116,721869','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '226','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('DOMPU'),'kode_sto' => 'DMP','alamat' => 'LEPADI','lat' => '-8,574591','long' => '116,485314','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '219','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('EMPANG'),'kode_sto' => 'EMP','alamat' => 'GAPIT','lat' => '-8,768574','long' => '117,939251','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '7,2','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SWETA'),'kode_sto' => 'SWE','alamat' => 'KERU NARMADA','lat' => '-8,594389','long' => '116,213928','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '6,1','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SELONG'),'kode_sto' => 'SEL','alamat' => 'KORLEKO','lat' => '-8,616953','long' => '116,607577','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '9,2','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SELONG'),'kode_sto' => 'SEL','alamat' => 'RENSING','lat' => '-8,72565','long' => '116,465027','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '12,4','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SELONG'),'kode_sto' => 'SEL','alamat' => 'SURABAYA LEPAK','lat' => '-8,707479','long' => '116,505221','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '8,1','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SELONG'),'kode_sto' => 'SEL','alamat' => 'KERUAK 2','lat' => '-8,774031','long' => '116,473669','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '16,4','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('PRAYA'),'kode_sto' => 'PYA','alamat' => 'LABULIA','lat' => '-8,6922076','long' => '116,1659163','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '13,8','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('PRAYA'),'kode_sto' => 'PYA','alamat' => 'DAREK','lat' => '-8,73807','long' => '116,20895','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '9,3','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('PRAYA'),'kode_sto' => 'PYA','alamat' => 'JONGGAT','lat' => '-8,651599','long' => '116,198796','merk' => NULL,'tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => NULL,'uplink' => 'NEED CONFIRMATION','metro' => NULL,'jarak_sto' => '12,7','sitac' => NULL,'jml_odp' => NULL,'kebutuhan' => NULL,'prioritas' => NULL,'propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('TENTE'),'kode_sto' => 'TEN','alamat' => 'Dadibou Tente,STO Tente','lat' => '-8,561213','long' => '118,668709','merk' => 'NOKIA','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-BIM','jarak_sto' => '40','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('MATARAM'),'kode_sto' => 'MTR','alamat' => 'Labuapi (ODC-MTR-FCU] STO Mataram','lat' => '-8,639574','long' => '116,095547','merk' => 'NOKIA','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MTR','jarak_sto' => '20','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('MATARAM'),'kode_sto' => 'MTR','alamat' => 'Kekeri (ODC-MTR-FAP] STO Mataram','lat' => '-8,551987','long' => '116,110942','merk' => 'NOKIA','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MTR','jarak_sto' => '10','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('GERUNG'),'kode_sto' => 'GER','alamat' => 'Lembar (ODC-GER-FAC] STO Gerung, mataram','lat' => '-8,726425','long' => '116,075419','merk' => 'NOKIA','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-GER','jarak_sto' => '20','sitac' => 'YES','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SELONG'),'kode_sto' => 'SEL','alamat' => 'Wanasaba,STO Selong','lat' => '-8,574632','long' => '116,550714','merk' => 'NOKIA','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-SEL','jarak_sto' => '25','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('BIMA'),'kode_sto' => 'BIM','alamat' => 'Wera Ambalawi','lat' => '-8,323001','long' => '118,771262','merk' => 'NOKIA','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-BIM','jarak_sto' => '35','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SELONG'),'kode_sto' => 'SEL','alamat' => 'Pringgabaya 2','lat' => '-8,560572','long' => '116,630563','merk' => 'NOKIA','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-SEL','jarak_sto' => '45','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SENGGIGI'),'kode_sto' => 'SGG','alamat' => 'SANTONG','lat' => '-8,256155','long' => '116,260613','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-SGG','jarak_sto' => '55','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('ALAS'),'kode_sto' => 'ALA','alamat' => 'LABUAN MAPIN (ODC-ALA-FAC]','lat' => '-8,52182','long' => '116,942248','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-ALA','jarak_sto' => '12','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => 'Apr-22'],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('MALUK'),'kode_sto' => 'MLK','alamat' => 'ODC-MLK-FAC','lat' => '-8,965648','long' => '116,759752','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME-D5-MLK','jarak_sto' => '12','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'STTF & TELKOMSEL','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => 'Apr-22'],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTB'),'sto_id' => UsulanOLTSeeder::findSTO('SUMBAWA'),'kode_sto' => 'SBW','alamat' => 'PENYARING NORTH MOYO (SUPPORT MXGP 2022]','lat' => '-8,4129','long' => '117,450428','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'YES','metro' => 'ME2-D5-SBW','jarak_sto' => '11','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'SUPPORT MXGP 2022','prioritas' => 'P1','propose_box' => NULL,'jadwal_order' => 'Apr-22'],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('BAJAWA'),'kode_sto' => 'BJW','alamat' => 'NAGEKEO','lat' => '-8,56667','long' => '121,265','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'Y','metro' => 'Y','jarak_sto' => '42.1 km','sitac' => 'YES','jml_odp' => '20','kebutuhan' => 'PROJECT NODE B','prioritas' => '1','propose_box' => NULL,'jadwal_order' => 'April 2022, preorder thp3'],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('ATAMBUA'),'kode_sto' => 'ATB','alamat' => 'ATAPUPU','lat' => '-8,9981','long' => '124,863261','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'Y','metro' => 'Y','jarak_sto' => '14.2 km','sitac' => 'YES','jml_odp' => '21','kebutuhan' => 'PROJECT HEM','prioritas' => '1','propose_box' => NULL,'jadwal_order' => 'April 2022, preorder thp3'],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('LARANTUKA'),'kode_sto' => 'LRT','alamat' => 'PERTAMINA LARANTUKA','lat' => '-8,325583141','long' => '122,9252012','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'Y','metro' => 'NOT READY (PORT HABIS]','jarak_sto' => '10.2 km','sitac' => 'NO','jml_odp' => '11','kebutuhan' => 'STTF-1 BATCH 2','prioritas' => '1','propose_box' => NULL,'jadwal_order' => 'April 2022, preorder thp3'],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('OESAPA'),'kode_sto' => 'OSP','alamat' => 'BSC TELKOSEL BIMOKU','lat' => '-10,149809','long' => '123,67543','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '4.2 km','sitac' => 'YES','jml_odp' => NULL,'kebutuhan' => 'BACKUP SENGKETA STO OESAPA','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('OESAPA'),'kode_sto' => 'OSP','alamat' => 'ODC FF OSP AU','lat' => '-10,149809','long' => '123,668925','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '3.1 km','sitac' => 'YES','jml_odp' => NULL,'kebutuhan' => 'BACKUP SENGKETA STO OESAPA','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('KUPANG'),'kode_sto' => 'KPN','alamat' => 'PERUM BTN KHOLHUA','lat' => '-10,195857','long' => '123,624524','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '6.1 km','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'BACKUP SENGKETA STO OESAPA','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('KUPANG'),'kode_sto' => 'KPN','alamat' => 'JALUR 40 RS BEREMEUS','lat' => '-10,208675','long' => '123,613039','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '6.4 km','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'BACKUP SENGKETA STO OESAPA','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('KUPANG'),'kode_sto' => 'KPN','alamat' => 'SIKUMANA-OEPURA','lat' => '-10,19876','long' => '123,605225','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '5.1 km','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'BACKUP SENGKETA STO OESAPA','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('KUPANG'),'kode_sto' => 'KPN','alamat' => 'TABUN-MANULAY','lat' => '-10,226824','long' => '123,570186','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '9.1 km','sitac' => 'NO','jml_odp' => NULL,'kebutuhan' => 'BACKUP SENGKETA STO OESAPA','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('ENDE'),'kode_sto' => 'END','alamat' => 'WOLOWONA','lat' => '-8,834173','long' => '121,67797','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '5.5 km','sitac' => 'NO','jml_odp' => '13','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('MAUMERE'),'kode_sto' => 'MMR','alamat' => 'NANGAHURE','lat' => '-8,562759','long' => '122,157998','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '11.1 km','sitac' => 'NO','jml_odp' => '13','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('ATAMBUA'),'kode_sto' => 'ATB','alamat' => 'MOTAAIN','lat' => '-9,569861','long' => '124,491992','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '69.1 km','sitac' => 'NO','jml_odp' => '21','kebutuhan' => 'PROJECT HEM','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('KPN'),'kode_sto' => 'KPN','alamat' => 'CAMPLONG','lat' => '-10,047379','long' => '123,901628','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '70.1 km','sitac' => 'NO','jml_odp' => '12','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('BAA'),'kode_sto' => 'BAA','alamat' => 'PANTAI BARU','lat' => '-10,629919','long' => '123,234655','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '25.4 km','sitac' => 'NO','jml_odp' => '10','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('BAA'),'kode_sto' => 'BAA','alamat' => 'PANTAI BO,A','lat' => '-10,929933','long' => '122,841387','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '33.1 km','sitac' => 'NO','jml_odp' => '11','kebutuhan' => 'PROJECT HEM','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('KUPANG'),'kode_sto' => 'KPN','alamat' => 'SATRAD BURAEN','lat' => '-10,289763','long' => '123,849992','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'Y','uplink' => 'Y','metro' => 'Y','jarak_sto' => '33.1 km','sitac' => 'YES','jml_odp' => '27','kebutuhan' => 'PROJECT HEM','prioritas' => '1','propose_box' => NULL,'jadwal_order' => 'April 2022, preorder thp3'],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('RUTENG'),'kode_sto' => 'RTE','alamat' => 'KISOL MBORONG','lat' => '-8,809595','long' => '120,663285','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '32 km','sitac' => 'NO','jml_odp' => '30','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('KUPANG'),'kode_sto' => 'KPN','alamat' => 'TAKARI','lat' => '-9,975852','long' => '124,08205','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '59.1 km','sitac' => 'NO','jml_odp' => '19','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('RUTENG'),'kode_sto' => 'RTE','alamat' => 'PAGAL','lat' => '-8,500359','long' => '120,473795','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '14.6 km','sitac' => 'NO','jml_odp' => '9','kebutuhan' => 'USULAN VIP (RUMAH MENKOMINFO)','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('BAJAWA'),'kode_sto' => 'BJW','alamat' => 'SOA','lat' => '-8,709098','long' => '121,057168','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '14.2 km','sitac' => 'NO','jml_odp' => '58','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('ENDE'),'kode_sto' => 'END','alamat' => 'NANGARORO','lat' => '-8,786679','long' => '121,393367','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '30.3 km','sitac' => 'NO','jml_odp' => '9','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('RUTENG'),'kode_sto' => 'RTE','alamat' => 'MANO RUTENG','lat' => '-8,604928','long' => '120,541627','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '10.2 km','sitac' => 'NO','jml_odp' => '48','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('MAUMERE'),'kode_sto' => 'MMR','alamat' => 'KOTING','lat' => '-8,687519','long' => '122,190042','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '9.1 km','sitac' => 'NO','jml_odp' => '18','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('MAUMERE'),'kode_sto' => 'MMR','alamat' => 'TALIBURA 1','lat' => '-8,556383','long' => '122,509311','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '34.2 km','sitac' => 'NO','jml_odp' => '13','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('MAUMERE'),'kode_sto' => 'MMR','alamat' => 'TALIBURA 2','lat' => '-8,614544','long' => '122,411053','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '23.5 km','sitac' => 'NO','jml_odp' => '9','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('MAUMERE'),'kode_sto' => 'MMR','alamat' => 'NDONA','lat' => '-8,835581','long' => '121,686831','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '65 km','sitac' => 'NO','jml_odp' => '10','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('ATAMBUA'),'kode_sto' => 'SOE','alamat' => 'BATU PUTIH','lat' => '-9,97305','long' => '124,123161','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '24.1 km','sitac' => 'NO','jml_odp' => '12','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('ATAMBUA'),'kode_sto' => 'ATB','alamat' => 'LURASIK','lat' => '-9,276681','long' => '124,862608','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'Y','jarak_sto' => '21.7 km','sitac' => 'NO','jml_odp' => '11','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('ATAMBUA'),'kode_sto' => 'KEF','alamat' => 'NOEMUTI','lat' => '-9,569861','long' => '124,491992','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'N','jarak_sto' => '14.8 km','sitac' => 'NO','jml_odp' => '12','kebutuhan' => 'PROJECT FTTH','prioritas' => '2','propose_box' => NULL,'jadwal_order' => NULL],
            // ['witel_id' => UsulanOLTSeeder::findWitel('NTT'),'sto_id' => UsulanOLTSeeder::findSTO('BETUN'),'kode_sto' => 'BEN','alamat' => 'BESIKAMA','lat' => '-9,65083','long' => '124,919','merk' => 'ZTE','tipe' => NULL,'tahap_pemenuhan' => NULL,'pln' => 'NO','uplink' => 'OGP KONSTRUKSI','metro' => 'N','jarak_sto' => '16.3 km','sitac' => 'NO','jml_odp' => '10','kebutuhan' => 'PROJECT NODE B','prioritas' => '1','propose_box' => NULL,'jadwal_order' => NULL],
        ]);
    }

    public static function findWitel($namaWitel){
        return witel::where('nama_witel', '=', $namaWitel)->first()->id;
    }
 
    public static function findSTO($namaSTO){
        return sto::where('nama_sto', '=', $namaSTO)->first()->id;
    }
}
